### ISSUE TITLE
Directory structures messed up

### ISSUE THREAD

**Issue by LoganDark** [RoosterDragon/Desktop-Ponies#16]
On Unix, the directory separator is `/`. But the zip file uses `\` instead:

![](https://puu.sh/tPKum/7747e0a18f.png)
![](https://puu.sh/tPKvA/1c1cfaecb6.png)

I've written a Python script to justify these errors [here](https://github.com/RoosterDragon/Desktop-Ponies/files/753307/DirectoryFix.py.zip), I have tested it, and it seems to have worked so far.

**Comment by ngyikp** [comment]
Problem is with .NET `System.IO.Compression.ZipFile.CreateFromDirectory` function itself:
https://github.com/RoosterDragon/Desktop-Ponies/blob/812e97cba80b3624a339290f62a45f6f08236462/Release%20Tool/Program.cs#L498

Of course, there are workaround code:
https://stackoverflow.com/questions/27289115/system-io-compression-zipfile-net-4-5-output-zip-in-not-suitable-for-linux-mac

**Comment by RoosterDragon** [comment]
I've wondered why it seemed to cause such issues - great find, thanks!

**Comment by RoosterDragon** [comment]
Fixed in cf1b01a072e6282456dee85e6b91ac4195a697b3. Starting in .NET Framework 4.6.1, they changed this behaviour and it now uses a backslash by default, which is indeed much better! https://msdn.microsoft.com/en-us/library/mt712573.aspx

**Comment by LoganDark** [comment]
@RoosterDragon You seem to have gotten your terminology mixed up - the backslash `\` was the problem, they're switching to the forward slash `/` which will fix it! Lol

**Comment by RoosterDragon** [comment]
Yup :P
