### ISSUE TITLE
Very slow on Mac

### ISSUE THREAD

**Issue by LoganDark** [RoosterDragon/Desktop-Ponies#17]
Even with only one pony, my MacBook fails to render at a decent framerate and I see flicker all the time. With ponies like Rainbow Dash that do special effects, the framerate goes near 0 and the effects are glitchy.

**Comment by LoganDark** [comment]
It runs completely fine in Windows 10 on the same machine. This is likely a mono issue

**Comment by RoosterDragon** [comment]
No you're right, Desktop Ponies is sadly very slow on non-Windows systems. I suggest giving https://github.com/hidefromkgb/DPengine a go - it ought to be much faster.
