### ISSUE TITLE
The download link is broken

### ISSUE THREAD

**Issue by hidefromkgb** [RoosterDragon/Desktop-Ponies#19]
[This line](https://github.com/RoosterDragon/Desktop-Ponies/commit/fa5380a64c3d8b6ec4a23bdfcca676a8d4ea17ab#diff-0730bb7c2e8f9ea2438b52e419dd86c9L20) still has one instance of «1.60» left, rendering the link unusable.

**Comment by RoosterDragon** [comment]
Cheers for pointing that out. Fixed by c805bb0ab507ed899ddd07a5d0badb429fe09844.
