### ISSUE TITLE
Sound Not Working

### ISSUE THREAD

**Issue by EdwardHamHam** [RoosterDragon/Desktop-Ponies#32]
I got a new computer and now the sound on Desktop Ponies does not work whatsoever. Not on voice lines that should have it, or anywhere else. I have checked in both normal operations, and in the pony editor. I have checked settings to make sure it's enabled (no change from installation on old PC) and all other sounds on the PC in question work fine. 

Edit: it just occurred to me that I should mention that I have in fact checked the volume mixer when Desktop Ponies is in operation, and it doesn't show up. By which I mean it isn't in the volume mixer, or in the general sound settings either. 

Edit 2 (9/5/21): The issue appears to have fixed itself, sound now works again, even though I didn't knowingly change anything. Might have had something to do with Windows update, but I'm not sure.

**Comment by RoosterDragon** [comment]
Glad to hear it resolved itself. The sound does rely on a (very old) DirectX component, so it's not impossible a Windows Update may have fixed something there.
