### ISSUE TITLE
OBS Issues

### ISSUE THREAD

**Issue by Breenland** [RoosterDragon/Desktop-Ponies#33]
When trying to having this running while streaming, OBS can't appear to capture it without completely blocking the rest of the stream unless using display capture. If there was a way to have a way to their background window be transparent, that'd be awesome. 

Or any other workarounds would be cool to know as well!

**Comment by Breenland** [comment]
Nevermind, I figured out a way to do it utilizing a color key filter on the app. This works fine as long as you don't have any characters with that specific color, of course, but being able to customize a background color for the app would be wonderful!

**Comment by RoosterDragon** [comment]
The window IS transparent, but if you need to capture the window then maybe the transparent areas are getting ignored and showing up in black.

I have added a setting in the new version so you can adjust the background colour and make it visible if desired. You can also adjust the colour used whilst it is still transparent, which I'm hoping (but have not tested) would allow you to set an invisible colour which could be filtered out.

Hope that helps!

**Comment by Breenland** [comment]
Yea, the window is transparent but for some reason OBS captured a completely black window that the buddies walked around on. Thanks for the quick update, appreciate ya!
