### ISSUE TITLE
Sounds didnt appear to windows 10 (bug)

### ISSUE THREAD

**Issue by WilliamDuguay** [RoosterDragon/Desktop-Ponies#34]
i'm using windows 10 but i didnt hear every pony talk (in Volume mixer)

**Comment by RoosterDragon** [comment]
Try installing the [DirectX 9 redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=35) - sounds won't work without it.

**Comment by WilliamDuguay** [comment]
Ok, ima installing right away, this would work
Thanks btw

**Comment by WilliamDuguay** [comment]
oh it worked, Thanks :)
