### ISSUE TITLE
PTS doesn't speak

### ISSUE THREAD

**Issue by DylanFarstveet** [RoosterDragon/Desktop-Ponies#36]
Princess Twilight Sparkle doesn't say the voice lines, they appear silently

**Comment by Kanaju** [comment]
This also happens for me but with a lot of ponies. Some voice lines aren't said, while others cut off a bit at the start and then play. I don't have time to document which ponies but it is definitely a lot of them.

**Comment by Kanaju** [comment]
I vividly remember when I first downloaded the program back maybe 2020/2021 or so that this issue wasn't there. This is an issue that has cropped up and still hasn't been dealt with years down the line, if #35 is anything to go by. Hopefully this gets fixed soon.

**Comment by Kanaju** [comment]
Also tired installing DirectX, but it says I already have it so I've got no clue what the problem could be.

**Comment by RoosterDragon** [comment]
Do you experience different behaviour with v1.67 versus v1.68? The sound engine was changed between those two versions, so it'd be useful to know if it was working well in one version but not the other.

**Comment by Kanaju** [comment]
> Do you experience different behaviour with v1.67 versus v1.68? The sound engine was changed between those two versions, so it'd be useful to know if it was working well in one version but not the other.

Happy to report that v1.67 works fine. It's probably the new sound system acting up I'd assume. Never crossed my mind to try out a different version when initially having this problem. Hope I could be of help.

**Comment by DylanFarstveet** [comment]
Hello! Sorry, I didn't respond before. I've been busy with work. For me, this issue is just happening with Princess Twilight Sparkle. All other ponies seem to work fine

**Comment by RoosterDragon** [comment]
> Princess Twilight Sparkle doesn't say the voice lines, they appear silently

Princess Twilight Sparkle has no audio for their voice lines. So, you'll only get the speech bubble. Most characters don't have audio so this is to be expected.

In the pony editor, you can provide an audio file for any speech lines you're like to have audio, if you have such an audio file available.

> Happy to report that v1.67 works fine. It's probably the new sound system acting up I'd assume.

I haven't been able to replicate any audio issues myself so I'm at a loss for fixing the issues you are seeing. I would recommend continuing to use the 1.67 version if it is working well for you, that seems like a pragmatic solution.
