### ISSUE TITLE
Might want to suggest wine for linux in the readme

### ISSUE THREAD

**Issue by LyraLeFay** [RoosterDragon/Desktop-Ponies#37]
I am running this on ubuntu 24 with KDE plasma. I've found it runs a lot better when running it through wine compared to how the readme suggests. I thought it might be a good idea to add that as a suggestion for anyone having performance issues with it.

It is so good by the way. Makes me really smile

**Comment by RoosterDragon** [comment]
A nice suggestion, added via 1a943f3afad68e9c3e5739526113e107b4c19290, thanks.
