### ISSUE TITLE
Doesn't compile on Linux

### ISSUE THREAD

**Issue by KraXarN** [RoosterDragon/Desktop-Ponies#5]
When compiling I get the following error:

/usr/lib/mono/4.5/Microsoft.Common.targets: Error: Command 'robocopy "/home/kraxarn/Downloads/Desktop-Ponies-master/Content" "/home/kraxarn/Downloads/Desktop-Ponies-master/Desktop Ponies/bin/Debug//" /XO /MIR
IF errorlevel 4 exit /b %errorlevel%
exit /b 0' exited with code: 2. (Desktop Ponies)

**Comment by RoosterDragon** [comment]
You're probably the first to try building it on anything other than Windows!

This is just the Windows command to copy files from the Content folder to the output directory. You could remove it entirely and copy things manually, or you could try to write a variant that will work on your platform.

Hopefully it'll build aside from that. Good luck.

**Comment by KraXarN** [comment]
I know similar commands for the Linux platform, but i wasn't able to locate the part of the code or file that was calling the command.

Also, I just noticed there was some Mac stuff using Mono, so I thought it would be able to run on Linux as well :p

**Comment by RoosterDragon** [comment]
Run, yes. Compile - I guess you'll find out :)

The code is located inside a pre-build event for the Desktop Ponies project. If you're using an IDE you probably need to hunt inside the project settings to find it. If you're building manually look inside the .vbproj file for that section and adjust it.

**Comment by KraXarN** [comment]
I used the MonoDevelop IDE, since it was the only IDE that I could find to open the project.

I'm not able to try it out until this weekend, no I'll try to figure it out then

**Comment by RoosterDragon** [comment]
Closing for age.
