### ISSUE TITLE
command line arguments in readme

### ISSUE THREAD

**Issue by jilleJr** [RoosterDragon/Desktop-Ponies#7]
Would be good to find the command line arguments inside the readme
![image](https://cloud.githubusercontent.com/assets/2477952/11969295/e84ed8de-a917-11e5-8ec7-7633703781d7.png)
Instead of finding out from testing. :)

Also would be sweet if the `autostart` didn't view the menu at all (like it does while loading)

**Comment by RoosterDragon** [comment]
Added with 4468c12750c49e2e5156aca59a7d26d8089bdee0 and 34becc5ab8b94f16996470a8e39bdbbdb9997114, respectively. Thanks for the suggestion :)
