### ISSUE TITLE
Menu locked after autostart

### ISSUE THREAD

**Issue by jilleJr** [RoosterDragon/Desktop-Ponies#9]
Hello again ^^
Found a bug where if you start the application via autostart and then do "Return to Menu" on a pony, the menu is locked. Can't add nor remove ponies via the main menu.
![image](https://cloud.githubusercontent.com/assets/2477952/12004574/37754e72-ab64-11e5-8ae5-b9da493bee6a.png)

![image](https://cloud.githubusercontent.com/assets/2477952/12004578/7f25c9ea-ab64-11e5-9a00-d43177dc67d7.png)

Ooo also found another bug but I'm gonna put it in a separate issue :smile: #8

**Comment by RoosterDragon** [comment]
Fixed by 5c0fb34a88cad6c57e22592c9f141830bcedc985
